apiVersion: demo.terasky.com/v1alpha1
kind: PostgreSQLDatabase
metadata:
  annotations:
    terasky.backstage.io/source-info: >-
      {"pushToGit":true,"gitBranch":"main","gitRepo":"github.com?owner=vrabbi-backstage&repo=demo-gitops","gitLayout":"cluster-scoped","basePath":"kubestage-cls-01/sdf/PostgreSQLDatabase"}
    terasky.backstage.io/add-to-catalog: 'true'
    terasky.backstage.io/owner: group:default/all_users
    terasky.backstage.io/system: sdf
    terasky.backstage.io/source-file-url: >-
      https://github.com/vrabbi-backstage/demo-gitops/blob/main/kubestage-cls-01/sdf/PostgreSQLDatabase/sdf.yaml
  name: sdf
  namespace: sdf
spec:
  highAvailability: false
  storageGB: 20
  version: 16.2
  compositeDeletePolicy: Background
