apiVersion: example.crossplane.io/v1
kind: LegacyAppClaim
metadata:
  annotations:
    terasky.backstage.io/source-info: >-
      {"pushToGit":true,"gitBranch":"main","gitRepo":"github.com?owner=vrabbi-backstage&repo=demo-gitops","gitLayout":"cluster-scoped","basePath":"local-v2/asd/LegacyAppClaim"}
    terasky.backstage.io/add-to-catalog: 'true'
    terasky.backstage.io/owner: group:default/acc-skadden
    terasky.backstage.io/system: asd
    terasky.backstage.io/source-file-url: >-
      https://github.com/vrabbi-backstage/demo-gitops/blob/main/local-v2/asd/LegacyAppClaim/sdfsdfsdfsdf.yaml
  name: sdfsdfsdfsdf
  namespace: asd
spec:
  image: sdfsdf
  namespace: sdfsdf
  compositeDeletePolicy: Background
