apiVersion: ipam.cluster.x-k8s.io/v1alpha1
kind: IPAddressClaim
metadata:
  name: demo-04
  namespace: test
  annotations:
    terasky.backstage.io/source-info: >-
      {"pushToGit":true,"gitBranch":"main","gitRepo":"github.com?owner=vrabbi-backstage&repo=demo-gitops","gitLayout":"custom","basePath":"demo-custom/nested"}
    terasky.backstage.io/add-to-catalog: 'true'
    terasky.backstage.io/system: test
    terasky.backstage.io/source-file-url: >-
      https://github.com/vrabbi-backstage/demo-gitops/blob/main/demo-custom/nested/demo-04.yaml
spec:
  owner: group:default/allcompany
  poolRef:
    apiGroup: ipam.cluster.x-k8s.io/v1alpha1
    kind: InClusterIPPool
    name: demo-04
