apiVersion: demo.terasky.com/v1alpha1
kind: PostgreSQLDatabase
metadata:
  annotations:
    terasky.backstage.io/source-info: '{"pushToGit":true,"gitBranch":"main","gitRepo":"github.com?owner=vrabbi-backstage&repo=demo-gitops","gitLayout":"cluster-scoped","basePath":"kubestage-cls-01/default/PostgreSQLDatabase"}'
    terasky.backstage.io/add-to-catalog: "true"
    terasky.backstage.io/owner: group:default/allcompany
    terasky.backstage.io/system: default
    terasky.backstage.io/source-file-url: https://github.com/vrabbi-backstage/demo-gitops/blob/main/kubestage-cls-01/default/PostgreSQLDatabase/demo-db-01.yaml
  name: demo-db-01
  namespace: default
spec:
  highAvailability: true
  storageGB: 20
  version: 16.7
  compositeDeletePolicy: Background
